name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  android-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: NewsFeedApp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build (includes tests)
        run: ./gradlew build

      - name: Static analysis (detekt)
        run: ./gradlew detekt

      - name: Lint
        run: ./gradlew lint


      - name: Code Coverage
        run: ./gradlew jacocoTestReport

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: NewsFeedApp/app/build/outputs/apk/debug/*.apk
